### PR TITLE
Updated to 1.0.2

### PR DESCRIPTION
**Pull request by MasterModr**
Updated plugin dependencies to Spigot 1.16.5 and Bukkit 1.16.2.
Added whitelist integration: If a user is on the whitelist they bypass
the role check.
Added admforcelink command to bot. Usage: -admforcelink \<discord id\>
\<minecraft uuid\> This is useful if you have bedrock users joining
through Gyser and Floodgate.

### CODE REVIEW

**Comment by nichogx** [comment]
- This plugin is backwards-compatible to 1.12, so I see no reason to update the dependencies.
- I could accept the whitelist integration if it were made into a config, since some users might not want that.
- For the admforcelink command you mean it is useful to link directly by UUID? If so then IMO that would be better implemented in the already existing commands (link and admlink), by checking if the parameter is an UUID or MC username.

**Comment by MasterModr** [comment]
All good comments Ill work on changing the whitelist to a config variable and I do like the idea of using the same command but yes in my case and I can imagine others' cases there is a need to directly link a UUID. As for the dependencies I wasn't thinking that updating them removed the backwards compatibility so ill revert those.  Ill clean up the code and then submit a new pull request in a few days.

**Comment by nichogx** [comment]
Great! Thank you!

**Comment by nichogx** [comment]
Closing since no more activity.

**Pull request closed without merging**
